// Copyright (c) 2016-2022, The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0
[[spaces]]
== Spaces（空间）

[open,refpage='XrSpace',desc='Opaque handle to a space',type='handles',xrefs='xrCreateReferenceSpace xrCreateActionSpace XrReferenceSpaceCreateInfo XrActionSpaceCreateInfo xrDestroySpace']
--
在虚拟现实和增强现实中，XR 应用程序都有
核心需求，那就是将虚拟对象的位置映射到对应真实世界位置，在那里它们将被渲染。

**Spaces** 允许应用程序显式的 创建和指定 参考帧 。这些参考帧被选择用来跟踪真实世界 ，然后用于算出这些参考帧之间是如何随着时间相对移动的

include::../../generated/api/handles/XrSpace.txt[]

Spaces 使用 slink:XrSpace 句柄 表示， 句柄由应用程序创建，然后在API调用中使用。
每当应用程序调用一个返回坐标的函数，它会提供一个 slink:XrSpace 来指出 坐标表达所需的 参考帧。
同样的，当给一个函数提供坐标，应用程序需要 指出 运行时需要在 哪个 slink:XrSpace 下 对这些坐标进行解释。

OpenXR定义了一组众所周知的  **reference spaces（参考空间）** 以用于引导他们的空间推理。
这些参考空间是: `VIEW`, `LOCAL` and `STAGE`.
每一个参考空间都有明确的的定义，其确定了它的原点的位置及它的轴的方向


随着时间的推移 运行时的跟踪系统提高了它对世界的理解，使它 may: 独立跟踪空间。
例如，即使 `LOCAL` 空间和 `STAGE` 空间都将他们的原点映射到世界的静态位置，
一个具有inside-out跟踪系统的运行时 may: 对 每个空间中的原点引入轻微的调整来 
连续的空间，以使每个原点保持在适当的位置。

For example, even though a `LOCAL` space and a `STAGE` space each map their
origin to a static position in the world, a runtime with an inside-out
tracking system may: introduce slight adjustments to the origin of each
space on a continuous basis to keep each origin in place.

除了众所周知的参考空间，运行时还暴露了其它独立跟踪的空间，例如 pose action space 来跟踪 随着时间的推移的 运动控制器的姿势。

当一个或两个 spaces 在跟踪一个动态对象时，在每一帧 向 flink:xrLocateSpace 传入一个更新时间 会产生 一个 更新的 相对姿势。
例如，随着用户的手相对于 stage地板的预定义原点 相对移动，在 `STAGE` 参考空间 的 左手的 pose action space 的位置 在每一帧都会改变。
在其他XR API 中，通常会报告 对象 相对于 一些假定的 隐含的 全局空间的 姿态。这样的API要小心其并没有明确定义这样一个隐含的全局空间，因为它不适用于所有系统。

一些系统将不支持 `STAGE` space，而其他系统可能支持 `STAGE` space 在各种物理 stages 之间动态切换可用性。
为了满足这种广泛的可变性，"poses" 总是被描述为两个空间之间的关系。

一些设备在使用时会提高他们对世界的理解。
在后面的帧中， 通过 flink:xrLocateSpace 返回的位置 may: 随着时间的推移而改变
，即使对于跟踪静态对象的 spaces，也会调整target space 或 base space 的原点。

应用程序提交的 合成层 包括一个 slink:XrSpace，使运行时用来随时间定位该层。
合成层 的 slink:XrSpace 是相对 `VIEW` 参考空间。尽管对于 non-head-mounted 规格，他们可能没有 "display-locked"，合成层也是隐式的 "head-locked"（头部锁定）的。

--

[[reference-spaces]]
=== Reference Spaces（参考空间）

[open,refpage='XrReferenceSpaceType',desc='Reference space types',type='enums']
--
用于参考空间的 slink:XrSpace 句柄通过使用 flink:xrCreateReferenceSpace 创建。创建需要指定 参考空间的类型 以及一个在 定义在此 参考空间类型 下的 正常参考帧 的位姿。

Runtimes implement well-known reference spaces from
elink:XrReferenceSpaceType if they support tracking of that kind:
include::../../generated/api/enums/XrReferenceSpaceType.txt[]

可用的参考空间类型由 flink:xrEnumerateReferenceSpaces 指明。
注意，其他的spaces也可以被创建，例如pose action spaces可以由 flink:xrCreateActionSpace 创建。

.Enumerant Descriptions
****
* ename:XR_REFERENCE_SPACE_TYPE_VIEW.
  `VIEW` 空间跟踪视图原点，视图原点用于生成对于 主观察者 （or centroid of view origins if stereo）的视图变换，其中 +Y向上，+X 向右，-Z 向前。
  这个空间指向观察者的前方，没有结合用户的眼睛朝向，且并不是重力对齐的。
+
`VIEW` 空间主要用于从用户的透视到另一个空间进行投影，以获取目标射线，或者在渲染较小时头部锁定内容，例如十字线。
在`VIEW` 空间中渲染的内容 将停留在头戴设备上的固定点显示，如果太大，可能会让人不舒服。
为获得用于 渲染世界内容每一帧的 理想的视图和投影变换，，应用程序应该调用 flink:xrLocateViews
而不是使用这个空间。
+
Runtimes must: support this reference space.
* ename:XR_REFERENCE_SPACE_TYPE_LOCAL.
  `LOCAL`参考空间建立了一个世界锁定的原点,重力对齐以排除俯仰和滚动,
  `LOCAL` reference space establishes a world-locked origin,+Y 向上，+X 向右，-Z 向前.
   该空间锁定其初始位置和方向，运行时可以将其定义为应用程序启动时的初始位置或其他一些校准的零位置。
+
当应用程序需要渲染 *seated-scale* 时内容，不需要相对于物理楼地面定位时，`LOCAL` 空间很有用。
+
当用户需要 recenter `LOCAL` 空间时，运行时 may: 提供某些 对于 应用程序透明的 系统级 的 recenter 交互，但这会导致当前经调整的头空间成为新的`LOCAL`空间。
当发生这种 recenter 发生时，运行时 must: 排队slink:XrEventDataReferenceSpaceChangePending 事件，伴随的 recentered `LOCAL` 空间原点 只对 当 basetype:XrTime 参数大于或
等于该事件中提供的 pname:changeTime 的 flink:xrLocateSpace 或
flink:xrLocateViews 调用生效。 
+
当视图、控制器或其他空间遇到相对于`LOCAL` 空间的跟踪丢失时，运行时 should: 继续提供推断或 最后已知的 pname:position 和 pname:orientation 值。
例如，只要它对于应用程序使用该姿势是合理的，这些推断的姿势就可以基于颈部模型的更新，惯性航位的推算，或最后已知的位置。
While a runtime is providing position data, it must: continue to set
ename:XR_SPACE_LOCATION_POSITION_VALID_BIT and
ename:XR_VIEW_STATE_POSITION_VALID_BIT but it can: clear
ename:XR_SPACE_LOCATION_POSITION_TRACKED_BIT and
ename:XR_VIEW_STATE_POSITION_TRACKED_BIT to indicate that the position is
inferred or last-known in this way.
+
恢复跟踪后，运行时 should: 捕捉其他空间的姿势回到相对于 `LOCAL` 空间的原始原点的位置。
+
Runtimes must: support this reference space.
* ename:XR_REFERENCE_SPACE_TYPE_STAGE.
  `STAGE` 参考空间是一个由运行时定义的平面矩形空间，它是空的，并可以在上面四处走动。原点位于矩形中心的地板上，+Y 向上，X 轴和 Z 轴与矩形边缘对齐。如果用户尚未在 运行时指定的 UI 中定义此参考空间空间，则运行时may: 无法定位相对于 `STAGE` 参考空间的空间。
  应用程序可以使用 flink:xrGetReferenceSpaceBoundsRect 来确定
  `STAGE` 参考空间的 XZ 边界矩形的范围（如果已定义）。
+
当应用程序需要渲染 *standing-scale* 时内容（无界限） 或  *room-scale* 内容（有界限）是相对的
到物理地面 ，`STAGE` 空间很有用。
+
当用户 redefines 当前 `STAGE` 空间的原点或边界时，或者运行时切换到一个新的 `STAGE` 定义时，运行时 must：排队 slink:XrEventDataReferenceSpaceChangePending 事件，伴随的
新的 `STAGE` 空间原点仅对 当 basetype:XrTime 参数大于或
等于该事件中提供的 pname:changeTime 的 flink:xrLocateSpace 或
flink:xrLocateViews 的调用生效。
+
当视图、控制器或其他空间遇到相对于`STAGE` 空间的跟踪丢失时，运行时 should: 继续提供 推断或
最后已知的 pname:position 和 pname:orientation 值。
例如，只要它对于应用程序使用该姿势是合理的，这些推断的姿势可以基于颈部模型的更新，惯性航位的推算，或最后已知的位置。
While a runtime is providing position data, it must: continue to set
ename:XR_SPACE_LOCATION_POSITION_VALID_BIT and
ename:XR_VIEW_STATE_POSITION_VALID_BIT but it can: clear
ename:XR_SPACE_LOCATION_POSITION_TRACKED_BIT and
ename:XR_VIEW_STATE_POSITION_TRACKED_BIT to indicate that the position is
inferred or last-known in this way.
+
恢复跟踪后，运行时 should: 捕捉其他空间的姿势回到相对于 `STAGE` 空间的原始原点的位置。
****
--

[open,refpage='xrGetReferenceSpaceBoundsRect',desc='Gets the bounds rectangle of a reference space',type='protos',xrefs='xrCreateReferenceSpace']
--

XR 系统可能有 有限的真实世界空间范围。这是指用户在其内可以 在保持追踪的情况下 自由的移动。
应用程序可能希望获得这些边界，进而选择应用程序的行为或内容的放置，以保证用户可以在边界内拥有完善体验。
应用程序 can: 通过 flink:xrGetReferenceSpaceBoundsRect 获取 这些信息。

当 flink:xrGetReferenceSpaceBoundsRect 被调用时，它 should: 返回一个 在参考空间下的可用的，无障碍物的，下到地板的矩形范围。在此范围内，允许用户可以在保持被跟踪的同时自由移动。
返回的范围表示 轴对齐的边界盒子的尺寸。slink:XrExtent2Df::pname:width 和
slink:XrExtent2Df::pname:height 字段 对应所提供空间的X轴 和 Z轴，同时范围的中心在空间的原点。
不是所有的系统和空间都可能支持边界。
如果一个运行时不能为一个给定的空间提供边界，会返回ename:XR_SPACE_BOUNDS_UNAVAILABLE，并将pname:bounds 的所有字段设置为0.

返回的范围的表示 是对于 所提供的  elink:XrReferenceSpaceType 的正常原点。
当调用 flink:xrCreateReferenceSpace 时 返回的范围 must: 不包含任何由应用程序指定的原点偏移。

如果 传递的 pname:createInfo 中的 elink:XrReferenceSpaceType 不被 pname:session 支持，则运行时必须返回 ename:XR_ERROR_REFERENCE_SPACE_UNSUPPORTED。

当运行时将开始以更新的空间边界运行时，运行时 must: 对 相应的 的 slink:XrEventDataReferenceSpaceChangePending 事件进行排队。

include::../../generated/api/protos/xrGetReferenceSpaceBoundsRect.txt[]

.Parameter Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:session is a handle to an slink:XrSession previously created with
  flink:xrCreateSession.
* pname:referenceSpaceType is the reference space type whose bounds should
  be retrieved.
* pname:bounds is the returned space extents.
****

include::../../generated/validity/protos/xrGetReferenceSpaceBoundsRect.txt[]
--

[open,refpage='XrEventDataReferenceSpaceChangePending',desc='Notifies the application that a reference space is changing',type='structs',xrefs='xrCreateReferenceSpace XrReferenceSpaceType']
--

slink:XrEventDataReferenceSpaceChangePending 事件被发送给应用程序 来 通知 它，
一个参考空间的原点（或边界）正在改变。
其发生可能是由于 用户显式重新定位空间或者运行时切换到不同的空间定义。


事件所提供basetype:XrTime 参数 大于或等于  pname:changeTime时， flink:xrLocateSpace或 flink:xrLocateViews  被调用，参考空间改变  must: 仅 此时生效。

The reference space change must: only take effect for flink:xrLocateSpace or
flink:xrLocateViews calls whose basetype:XrTime parameter is greater than or
equal to the pname:changeTime provided in that event.

运行时 should: 提供 一个 pname:changeTim 给 应用程序，这允许对已经使用先前定义的空间的在执行的呈现帧使用深度渲染管道、

Runtimes should: provide a pname:changeTime to applications that allows for
a deep render pipeline to present frames that are already in flight using
the previous definition of the space.

运行时 should: 选在一个 pname:changeTime，其使用未来帧的 pname:displayTime 之间 的中间值，来避免 使用 pname:displayPeriod 计算 未来帧时间 的应用程序所产生的 阈值问题   

Runtimes should: choose a pname:changeTime that is midway between the
pname:displayTime of future frames to avoid threshold issues with
applications that calculate future frame times using pname:displayPeriod.


这里提供的 pname:pose must: 仅描述 参考空间的自然原点 的改变，且在调用 flink:xrCreateReferenceSpace时 must: 不包含由应用程序指定任何原点偏移。

The pname:pose provided here must: only describe the change in the natural
origin of the reference space and must: not incorporate any origin offsets
specified by the application during calls to flink:xrCreateReferenceSpace.

如果运行时不知道 空间的新原点与它之前原点的相对位置， pname:poseValid 应该为 false，
pname:poseInPreviousSpace的位置和方向应该时未定义。

If the runtime does not know the location of the space's new origin relative
to its previous origin, pname:poseValid must: be false, and the position and
orientation of pname:poseInPreviousSpace are undefined.

include::../../generated/api/structs/XrEventDataReferenceSpaceChangePending.txt[]

.Member Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:next is code:NULL or a pointer to the next structure in a structure
  chain.
  No such structures are defined in core OpenXR.
* pname:session is the slink:XrSession for which the reference space is
  changing.
* pname:referenceSpaceType is the elink:XrReferenceSpaceType that is
  changing.
* pname:changeTime is the target basetype:XrTime after which
  flink:xrLocateSpace or flink:xrLocateViews will return values that respect
  this change.
* pname:poseValid is true if the runtime can determine the pname:pose of the
  new space in the previous space before the change.
* pname:poseInPreviousSpace is an slink:XrPosef defining the position and
 orientation of the new reference space's natural origin within the natural
 reference frame of its previous space.
****

include::../../generated/validity/structs/XrEventDataReferenceSpaceChangePending.txt[]
--

=== Action Spaces（动作空间）
用于姿势动作的 slink:XrSpace 句柄是使用flink:xrCreateActionSpace 创建。创建通过指定选择的 姿势动作 和一个 在动作的正常参考帧下 的 姿势。

Runtimes support suggested pose action bindings to well-known user paths
with subpathname:/pose subpaths if they support tracking for that particular
identifier.

Some example well-known pose action paths:
****
* pathname:/user/hand/left/input/grip
* pathname:/user/hand/left/input/aim
* pathname:/user/hand/right/input/grip
* pathname:/user/hand/right/input/aim
****

For definitions of these well-known pose device paths, see the discussion of
<<semantic-path-input,device input subpaths>> in the Semantic Paths chapter.

[[spaces-action-spaces-lifetime]]
==== Action Spaces Lifetime（动作空间的生命周期）
slink:XrSpace handles created for a pose action must: be unlocatable unless
the action set that contains the corresponding pose action was set as active
via the most recent flink:xrSyncActions call.
If the underlying device that is active for the action changes, the device
this space is tracking must: only change to track the new device when
flink:xrSyncActions is called.

If flink:xrLocateSpace is called with an unlocatable action space, the
implementation must: return no position or orientation and both
ename:XR_SPACE_LOCATION_POSITION_VALID_BIT and
ename:XR_SPACE_LOCATION_ORIENTATION_VALID_BIT must: be unset.
If flink:xrLocateViews is called with an unlocatable action space, the
implementation must: return no position or orientation and both
ename:XR_VIEW_STATE_POSITION_VALID_BIT and
ename:XR_VIEW_STATE_ORIENTATION_VALID_BIT must: be unset.

[[space_lifecycle]]
=== Space Lifecycle（空间的生命周期）

There are a small set of core APIs that allow applications to reason about
reference spaces, action spaces, and their relative locations.

==== xrEnumerateReferenceSpaces

[open,refpage='xrEnumerateReferenceSpaces',desc='Enumerate available reference spaces',type='protos',xrefs='XrSpace']
--
The flink:xrEnumerateReferenceSpaces function is defined as:

include::../../generated/api/protos/xrEnumerateReferenceSpaces.txt[]

.Parameter Descriptions
****
* pname:session is a handle to an slink:XrSession previously created with
  flink:xrCreateSession.
* pname:spaceCapacityInput is the capacity of the spaces array, or 0 to
  indicate a request to retrieve the required capacity.
* pname:spaceCountOutput is a pointer to the count of spaces written, or a
  pointer to the required capacity in the case that pname:spaceCapacityInput
  is 0.
* pname:spaces is a pointer to an application-allocated array that will be
  filled with the enumerant of each supported reference space.
  It can: be code:NULL if pname:spaceCapacityInput is 0.
* See <<buffer-size-parameters, Buffer Size Parameters>> chapter for a
  detailed description of retrieving the required pname:spaces size.
****

Enumerates the set of reference space types that this runtime supports for a
given session.
Runtimes must: always return identical buffer contents from this enumeration
for the lifetime of the session.

If a session enumerates support for a given reference space type, calls to
flink:xrCreateReferenceSpace must: succeed for that session, with any
transient unavailability of poses expressed later during calls to
flink:xrLocateSpace.

include::../../generated/validity/protos/xrEnumerateReferenceSpaces.txt[]
--

==== xrCreateReferenceSpace

[open,refpage='xrCreateReferenceSpace',desc='Creates a reference space',type='protos',xrefs='XrSpace XrReferenceSpaceCreateInfo xrDestroySpace']
--
The flink:xrCreateReferenceSpace function is defined as:

include::../../generated/api/protos/xrCreateReferenceSpace.txt[]

.Parameter Descriptions
****
* pname:session is a handle to an slink:XrSession previously created with
  flink:xrCreateSession.
* pname:createInfo is the slink:XrReferenceSpaceCreateInfo used to specify
  the space.
* pname:space is the returned space handle.
****

Creates an slink:XrSpace handle based on a chosen reference space.
Application can: provide an slink:XrPosef to define the position and
orientation of the new space's origin within the natural reference frame of
the reference space.

Multiple slink:XrSpace handles may exist simultaneously, up to some limit
imposed by the runtime.
The slink:XrSpace handle must: be eventually freed via the
flink:xrDestroySpace function.

The runtime must: return ename:XR_ERROR_REFERENCE_SPACE_UNSUPPORTED if the
given reference space type is not supported by this pname:session.

include::../../generated/validity/protos/xrCreateReferenceSpace.txt[]
--

[open,refpage='XrReferenceSpaceCreateInfo',desc='Creation info for a reference space',type='structs',xrefs='XrSpace xrCreateReferenceSpace']
--
The slink:XrReferenceSpaceCreateInfo structure is defined as:

include::../../generated/api/structs/XrReferenceSpaceCreateInfo.txt[]

.Member Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:next is code:NULL or a pointer to the next structure in a structure
  chain.
  No such structures are defined in core OpenXR.
* pname:referenceSpaceType is the chosen elink:XrReferenceSpaceType.
* pname:poseInReferenceSpace is an slink:XrPosef defining the position and
  orientation of the new space's origin within the natural reference frame
  of the reference space.
****

include::../../generated/validity/structs/XrReferenceSpaceCreateInfo.txt[]
--

==== xrCreateActionSpace
[open,refpage='xrCreateActionSpace',desc='Creates a space based on a pose action',type='protos',xrefs='XrSpace XrActionSpaceCreateInfo xrDestroySpace']
--
The flink:xrCreateActionSpace function is defined as:

include::../../generated/api/protos/xrCreateActionSpace.txt[]

.Parameter Descriptions
****
* pname:session is the slink:XrSession to create the action space in.
* pname:createInfo is the slink:XrActionSpaceCreateInfo used to specify the
  space.
* pname:space is the returned space handle.
****

Creates an slink:XrSpace handle based on a chosen pose action.
Application can: provide an slink:XrPosef to define the position and
orientation of the new space's origin within the natural reference frame of
the action space.

Multiple slink:XrSpace handles may exist simultaneously, up to some limit
imposed by the runtime.
The slink:XrSpace handle must be eventually freed via the
flink:xrDestroySpace function or by destroying the parent slink:XrAction
handle.

The runtime must: return ename:XR_ERROR_ACTION_TYPE_MISMATCH if the action
provided in pname:action is not of type ename:XR_ACTION_TYPE_POSE_INPUT.

include::../../generated/validity/protos/xrCreateActionSpace.txt[]
--

[open,refpage='XrActionSpaceCreateInfo',desc='Creation info for an action space',type='structs',xrefs='XrSpace xrCreateActionSpace']
--
The slink:XrActionSpaceCreateInfo structure is defined as:

include::../../generated/api/structs/XrActionSpaceCreateInfo.txt[]

.Member Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:next is code:NULL or a pointer to the next structure in a structure
  chain.
  No such structures are defined in core OpenXR.
* pname:action is a handle to a pose slink:XrAction previously created with
  flink:xrCreateAction.
* pname:subactionPath is dlink:XR_NULL_PATH or an basetype:XrPath that was
  specified when the action was created.
  If pname:subactionPath is a valid path not specified when the action was
  created the runtime must: return ename:XR_ERROR_PATH_UNSUPPORTED.
  If this parameter is set, the runtime must: create a space that is
  relative to only that subaction's pose binding.
* pname:poseInActionSpace is an slink:XrPosef defining the position and
  orientation of the new space's origin within the natural reference frame
  of the pose action.
****

include::../../generated/validity/structs/XrActionSpaceCreateInfo.txt[]
--

==== xrDestroySpace

[open,refpage='xrDestroySpace',desc='Creates a space based on a pose action',type='protos',xrefs='XrSpace xrCreateReferenceSpace xrCreateActionSpace']
--
The flink:xrDestroySpace function is defined as:

include::../../generated/api/protos/xrDestroySpace.txt[]

.Parameter Descriptions
****
* pname:space is a handle to an slink:XrSpace previously created by a
  function such as flink:xrCreateReferenceSpace.
****

slink:XrSpace handles are destroyed using flink:xrDestroySpace.
The runtime may: still use this space if there are active dependencies (e.g,
compositions in progress).

include::../../generated/validity/protos/xrDestroySpace.txt[]
--

[[locating_spaces]]
=== Locating Spaces（定位空间）

应用程序使用 flink:xrLocateSpace 函数来查找 某link:XrSpace 的原点的位姿。这是在某基空间 slink:XrSpace 下的给定历史时间或预测时间 的查找 。
如果一个应用程序想要知道这个空间原点的速度，它 can: 在调用  flink:xrLocateSpace 函数时， 将 一个 slink:XrSpaceVelocity 结构体 链接 slink:XrSpaceLocation 结构体的  pname:next 指针上。

应用程序 hould:： 检查输出的 elink:XrSpaceLocationFlagBits 和 elink:XrSpaceVelocityFlagBits 来判断位置的组成部分有效性和跟踪状态。

==== xrLocateSpace

[open,refpage='xrLocateSpace',desc='Locates a space with reference to another space',type='protos',xrefs='XrSpace XrSpaceLocationFlags']
--
flink:xrLocateSpace provides the physical location of a space in a base
space at a specified time, if currently known by the runtime.

include::../../generated/api/protos/xrLocateSpace.txt[]

.Parameter Descriptions
****
* pname:space identifies the target space to locate.
* pname:baseSpace identifies the underlying space in which to locate
  pname:space.
* pname:time is the time for which the location should be provided.
* pname:location provides the location of pname:space in pname:baseSpace.
****

For a pname:time in the past, the runtime should: locate the spaces based on
the runtime's most accurate current understanding of how the world was at
that historical time.

For a pname:time in the future, the runtime should: locate the spaces based
on the runtime's most up-to-date prediction of how the world will be at that
future time.

The minimum valid range of values for pname:time are described in
<<prediction-time-limits>>.
For values of pname:time outside this range, flink:xrLocateSpace may: return
a location with no position and ename:XR_SPACE_LOCATION_POSITION_VALID_BIT
unset.

Some devices improve their understanding of the world as the device is used.
The location returned by flink:xrLocateSpace for a given pname:space,
pname:baseSpace and pname:time may: change over time, even for spaces that
track static objects, as one or both spaces adjust their origins.

During tracking loss of pname:space relative to pname:baseSpace, runtimes
should: continue to provide inferred or last-known pname:position and
pname:orientation values.
These inferred poses can, for example, be based on neck model updates,
inertial dead reckoning, or a last-known position, so long as it is still
reasonable for the application to use that pose.
While a runtime is providing position data, it must: continue to set
ename:XR_SPACE_LOCATION_POSITION_VALID_BIT but it can: clear
ename:XR_SPACE_LOCATION_POSITION_TRACKED_BIT to indicate that the position
is inferred or last-known in this way.

If the runtime has not yet observed even a last-known pose for how to locate
pname:space in pname:baseSpace (e.g. one space is an action space bound to a
motion controller that has not yet been detected, or the two spaces are in
disconnected fragments of the runtime's tracked volume), the runtime should:
return a location with no position and
ename:XR_SPACE_LOCATION_POSITION_VALID_BIT unset.

The runtime must: return a location with both
ename:XR_SPACE_LOCATION_POSITION_VALID_BIT and
ename:XR_SPACE_LOCATION_POSITION_TRACKED_BIT set when locating pname:space
and pname:baseSpace if both spaces were created relative to the same entity
(e.g. two action spaces for the same action), even if the entity is
currently untracked.
The location in this case is the difference in the two spaces'
application-specified transforms relative to that common entity.

The runtime should: return a location with
ename:XR_SPACE_LOCATION_POSITION_VALID_BIT set and
ename:XR_SPACE_LOCATION_POSITION_TRACKED_BIT unset for spaces tracking two
static entities in the world when their relative pose is known to the
runtime.
This enables applications to make use of the runtime's latest knowledge of
the world, even during tracking loss.

If an slink:XrSpaceVelocity structure is chained to the pname:next pointer
of slink:XrSpaceLocation and the velocity is observed or can be calculated
by the runtime, the runtime must: fill in the linear velocity of the origin
of space within the reference frame of pname:baseSpace and set the
ename:XR_SPACE_VELOCITY_LINEAR_VALID_BIT.
Similarly, if an slink:XrSpaceVelocity structure is chained to the
pname:next pointer of slink:XrSpaceLocation and the angular velocity is
observed or can be calculated by the runtime, the runtime must: fill in the
angular velocity of the origin of space within the reference frame of
pname:baseSpace and set the ename:XR_SPACE_VELOCITY_ANGULAR_VALID_BIT.

[[example_locate_space_code]]
The following example code shows how an application can get both the
location and velocity of a space within a base space using the
flink:xrLocateSpace function by chaining an slink:XrSpaceVelocity to the
next pointer of slink:XrSpaceLocation and calling flink:xrLocateSpace.

[source,C++]
----
XrSpace space;      // previously initialized
XrSpace baseSpace;  // previously initialized
XrTime time;        // previously initialized

XrSpaceVelocity velocity {XR_TYPE_SPACE_VELOCITY};
XrSpaceLocation location {XR_TYPE_SPACE_LOCATION, &velocity};
xrLocateSpace(space, baseSpace, time, &location);
----

include::../../generated/validity/protos/xrLocateSpace.txt[]
--


[open,refpage='XrSpaceLocation',desc='Contains info about a space's location',type='structs',xrefs='XrSpace xrLocateSpace XrSpaceLocationFlags XrSpaceVelocity']
--
The slink:XrSpaceLocation structure is defined as:

include::../../generated/api/structs/XrSpaceLocation.txt[]

.Member Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:next is code:NULL or a pointer to the next structure in a structure
  chain, such as slink:XrSpaceVelocity.
* pname:locationFlags is a bitfield, with bit masks defined in
  elink:XrSpaceLocationFlagBits, to indicate which members contain valid
  data.
  If none of the bits are set, no other fields in this structure should: be
  considered to be valid or meaningful.
* pname:pose is an slink:XrPosef defining the position and orientation of
  the origin of flink:xrLocateSpace::pname:space within the reference frame
  of flink:xrLocateSpace::pname:baseSpace.
****

include::../../generated/validity/structs/XrSpaceLocation.txt[]
--

[open,refpage='XrSpaceLocationFlags',desc='Space location flags',type='flags',xrefs='XrSpaceLocation']
--
The pname:locationFlags member is a bitwise-OR of zero or more of the
following flags:

include::../../generated/api/enums/XrSpaceLocationFlagBits.txt[]

where the flags have the following meaning:

.Flag Descriptions
****
* ename:XR_SPACE_LOCATION_ORIENTATION_VALID_BIT indicates that the
  pname:pose field's pname:orientation field contains valid data.
  For a space location tracking a device with its own inertial tracking,
  ename:XR_SPACE_LOCATION_ORIENTATION_TRACKED_BIT should: remain set when
  this bit is set.
  Applications must: not read the pname:pose field's pname:orientation if
  this flag is unset.
* ename:XR_SPACE_LOCATION_POSITION_VALID_BIT indicates that the pname:pose
  field's pname:position field contains valid data.
  When a space location loses tracking, runtimes should: continue to provide
  valid but untracked pname:position values that are inferred or last-known,
  so long as it's still meaningful for the application to use that position,
  clearing ename:XR_SPACE_LOCATION_POSITION_TRACKED_BIT until positional
  tracking is recovered.
  Applications must: not read the pname:pose field's pname:position if this
  flag is unset.
* ename:XR_SPACE_LOCATION_ORIENTATION_TRACKED_BIT indicates that the
  pname:pose field's pname:orientation field represents an actively tracked
  orientation.
  For a space location tracking a device with its own inertial tracking,
  this bit should: remain set when
  ename:XR_SPACE_LOCATION_ORIENTATION_VALID_BIT is set.
  For a space location tracking an object whose orientation is no longer
  known during tracking loss (e.g. an observed QR code), runtimes should:
  continue to provide valid but untracked pname:orientation values, so long
  as it's still meaningful for the application to use that orientation.
* ename:XR_SPACE_LOCATION_POSITION_TRACKED_BIT indicates that the pname:pose
  field's pname:position field represents an actively tracked position.
  When a space location loses tracking, runtimes should: continue to provide
  valid but untracked pname:position values that are inferred or last-known,
  e.g. based on neck model updates, inertial dead reckoning, or a last-known
  position, so long as it's still meaningful for the application to use that
  position.
****
--

[open,refpage='XrSpaceVelocity',desc='Contains info about a space's linear and angular velocity',type='structs',xrefs='XrSpaceLocation XrSpace xrLocateSpace XrSpaceVelocityFlags']
--

The slink:XrSpaceVelocity structure is defined as:

include::../../generated/api/structs/XrSpaceVelocity.txt[]

.Member Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:next is code:NULL or a pointer to the next structure in a structure
  chain.
  No such structures are defined in core OpenXR.
* pname:velocityFlags is a bitfield, with bit masks defined in
  elink:XrSpaceVelocityFlagBits, to indicate which members contain valid
  data.
  If none of the bits are set, no other fields in this structure should: be
  considered to be valid or meaningful.
* pname:linearVelocity is the relative linear velocity of the origin of
  flink:xrLocateSpace::pname:space with respect to and expressed in the
  reference frame of flink:xrLocateSpace::pname:baseSpace, in units of
  meters per second.
* pname:angularVelocity is the relative angular velocity of
  flink:xrLocateSpace::pname:space with respect to
  flink:xrLocateSpace::pname:baseSpace.
  The vector's direction is expressed in the reference frame of
  flink:xrLocateSpace::pname:baseSpace and is parallel to the rotational
  axis of flink:xrLocateSpace::pname:space.
  The vector's magnitude is the relative angular speed of
  flink:xrLocateSpace::pname:space in radians per second.
  The vector follows the right-hand rule for torque/rotation.
****

include::../../generated/validity/structs/XrSpaceVelocity.txt[]
--

[open,refpage='XrSpaceVelocityFlags',desc='Space velocity flags',type='flags',xrefs='XrSpaceVelocity']
--
The pname:velocityFlags member is a bitwise-OR of zero or more of the
following flags:

include::../../generated/api/enums/XrSpaceVelocityFlagBits.txt[]

where the flags have the following meaning:

include::../../generated/api/enums/XrSpaceVelocityFlagBits.comments.txt[]

--

